apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.kubevirt.io/rhel9.0: Red Hat Enterprise Linux 9.0 or higher
  name: rhel9-contemporary-chipmunk
  namespace: openshift
  labels:
    app: rhel9-contemporary-chipmunk
    flavor.template.kubevirt.io/small: 'true'
    os.template.kubevirt.io/rhel9.0: 'true'
    vm.kubevirt.io/template: rhel9-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.19.6
    workload.template.kubevirt.io/server: 'true'
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: rhel9-contemporary-chipmunk-rootdisk-5hfef
      spec:
        source:
          pvc:
            name: rhel9-2a70e7a1fadc
            namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: '32212254720'
          storageClassName: ocs-storagecluster-ceph-rbd
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        flavor.template.kubevirt.io/small: 'true'
        kubevirt.io/domain: rhel9-contemporary-chipmunk
        kubevirt.io/size: small
        os.template.kubevirt.io/rhel9.0: 'true'
        vm.kubevirt.io/name: rhel9-contemporary-chipmunk
        workload.template.kubevirt.io/server: 'true'
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - macAddress: '02:7d:80:00:00:02'
              masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      hostname: rhel9-contemporary-chipmunk
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - configMap:
            name: platform
          name: environment-disk-ozre5w
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              password: '{{ password }}'
              chpasswd:
                expire: false
              ssh_authorized_keys: >
                {{ sshPubKey }}
          name: cloudinitdisk
        - dataVolume:
            name: rhel9-contemporary-chipmunk-rootdisk-5hfef
          name: rootdisk
